- kubejs/server_scripts/main_server_script.js
- kubejs/server_scripts/toolbelt/recipes.js
pr направленый на изменение крафтов в моде toolbelt
> toolbelt mod

- kubejs/server_scripts/tfc/recipes.js
сделал крафты алебастровых кирпичей и сырого камня алебастра, также добавил крафты для цветных видов алебастра
Исправления: #279
> Рецепты алебастра через гт машины и тд

- kubejs/server_scripts/tfc/tags.js
Now spades can be put on the tool racks.
> Now spades can be put on the tool racks

- config/ftbquests/quests/chapters/ae2.snbt
- config/ftbquests/quests/chapters/cc.snbt
- config/ftbquests/quests/chapters/create.snbt
- config/ftbquests/quests/chapters/ev__extreme_voltage.snbt
- config/ftbquests/quests/chapters/hv__high_voltage.snbt
- config/ftbquests/quests/chapters/iv__insane_voltage.snbt
- config/ftbquests/quests/chapters/luv__ludicrous_voltage.snbt
- config/ftbquests/quests/chapters/lv__low_voltage.snbt
- config/ftbquests/quests/chapters/multiblock_dilemma.snbt
- config/ftbquests/quests/chapters/mv__medium_voltage.snbt
- config/ftbquests/quests/chapters/primitive_age.snbt
- config/ftbquests/quests/chapters/progression.snbt
- config/ftbquests/quests/chapters/steam_age.snbt
- config/ftbquests/quests/chapters/uv__ultimate_voltage.snbt
- config/ftbquests/quests/chapters/zpm__zero_point_module.snbt
- kubejs/assets/tfg/lang/en_us.json
Translation of quests
Перевод квестов
> Translation of quests

- config/fancymenu/customization/gui_main_menu.txt
Small PR for a typo that was bothering me in the menu lol, let me know if I missed something
> fix: typo in main menu

- kubejs/server_scripts/tfc/data.js
Fix misplaced chemical values for saltpetre fertilizer
Исправьте неправильные значения химикатов для удобрения селитры
> Fix Saltpetre Fertilizer Values

- kubejs/server_scripts/firmalife/recipes.js
фикс рецепта спринклера, который одинаков с рецептом медного краника
> Sprinkler fix

- kubejs/server_scripts/firmalife/recipes.js
Added GT mixer and Create mixer recipes for more yeast starter
Added recipes to turn GT cocoa powder into Firmalife cocoa dust, otherwise it's impossible to make chocolate
> Added yeast starter and cocoa powder recipes

- kubejs/server_scripts/tfc/recipes.js
Finish olive oil chain in gtceu machines
Added 2 new gtceu recipes repeating firmalife barrel recipe in kubejs
New way to produce olive oil
> Olive oil in machines

- kubejs/server_scripts/gregtech/recipes.js
> Fixed mixer recipes for red/blue steel

- kubejs/server_scripts/create/recipes.js
Makes them less silly to craft when you're in later tiers
> Added another recipe for Create's electron tubes

- kubejs/server_scripts/tfc/recipes.js
- kubejs/server_scripts/tfc/tags.js
- kubejs/startup_scripts/tfc/constants.js
Added cheese prodcution line to gtceu machines
Also added tomato sauce and cream
Handwritten recipes
- New way to make rennet plants and biomass
- Dissolving tomato sauce using mixer
- Full cheese production in machines
No, just simple recipes
> Electric cheese, tomato sauce and cream

- kubejs/server_scripts/tfc/recipes.js
Leather production chain in gtceu machines
Handwritten recipes repeating steps from barrel leather production chain
15 new leather related recipes
Hope not, just handwritten recipes
> electric leather

- kubejs/server_scripts/minecraft/recipes.js
- kubejs/startup_scripts/gtceu/constants.js
This got lost in a merge or something
> Added missing recipe for nether brick

- kubejs/server_scripts/tfc/recipes.js
- kubejs/startup_scripts/main_startup_script.js
Исправил опечатку в температуре кипения морской воды для рецепта маленькой кучки соли с 1000 на 100 (Fixed a typo in salt water boiling recipe's temperature for small salt pile - 1000 > 100)
> Исправил опечатку в температуре кипения морской воды для рецепта маленькой кучки соли с 1000 на 100

- kubejs/server_scripts/gregtech/recipes.js
Forgot to fix these in #696, now they are consistent
> Fixed colored steel dust centrifuge recipes

- kubejs/server_scripts/greate/recipes.js
Recipes work without being in a cleanroom
> Remove Saw Cutter until fix for Cleanroom

- kubejs/server_scripts/greate/recipes.removes.js
Waiting for a fix from Greate about cleanroom recipe working without being in a cleanroom
> Removing Mechanical Saw HV+

- config/ftbquests/quests/chapters/questssteam_age.snbt
Remove some quests around the first electronic circuit because they are implemented within LV Age now
> Update quests steam_age

- config/ftbquests/quests/chapters/lv__low_voltage.snbt
Lots of change to take into consideration Greate
> Big update for LV Quests

- kubejs/server_scripts/tfc/recipes.machines.js
Barrel is 2B Milk 1 renet for 2B Curdled in the barrel so fixed to be the same
> Fix Curdled milk recipes to be the same as the barrel

- kubejs/server_scripts/tfc/recipes.machines.js
- kubejs/startup_scripts/tfc/constants.js
It was two olives when it should be one.
> Add Brine/Vinegar to GT Machines and Fix Olive Oil recipe to fit with VAT recipe

- config/ftbquests/quests/chapters/queststfc_tips.snbt
Fixes minor spelling errors in translation keys
No more missing localisation because of silly mistakes.
**Discord**: algol_rithm
> Fxed some more translation key errors in tfg_tips

- kubejs/server_scripts/ad_astra/recipes.js
- kubejs/server_scripts/ad_astra/tags.js
- kubejs/startup_scripts/tfg/materials.js
Changed the recipe for the tier 1 rocket so it needs:
-Assembler and no longer NASA Workbench
-Creating a new alloy for rocket
-Changed the cone to use new alloy, polyethylene and HV Emitter so Eye of Ember is needed
-Changed the Fin so they need rocket alloy t1 and stainless steel in an alloy smelter. Trying to give more motivation to make the multi-smelter
-Steel engine needs Blue steel
-Creation of vitrified amiante as an alternative to borosilicate dust made with Asbestos and Pyrolise oven also a tag for insulation tier 1
> New crafting process for the Tier 1 Rocket

- kubejs/server_scripts/gregtech/recipes.js
no more circuits
Рецепт всё равно всего один, нет смысла добавлять режим
> salt water fast fix

- config/ftbquests/quests/chapters/ae2.snbt
- config/ftbquests/quests/chapters/ev__extreme_voltage.snbt
- config/ftbquests/quests/chapters/gregtech_energy.snbt
- config/ftbquests/quests/chapters/hv__high_voltage.snbt
- config/ftbquests/quests/chapters/mv__medium_voltage.snbt
- kubejs/server_scripts/gregtech/recipes.removes.js
HV Chapter with moon done, fix for Eye of Ender and some fixes for quest for better HV Integration.
Maybe an issue on the MV Chapter unclear with oil can be fixed after that.
I'm pushing but lang formate will need to be done later on.
> HV Quests in eng and fixes for others quests and HV integration

- config/ftbquests/quests/chapters/hv__high_voltage.snbt
- kubejs/server_scripts/gregtech/data.js
- kubejs/server_scripts/gregtech/recipes.machines.js
-Recipes for each Bedrock Miner (at HV, IV and ZPM)
-Bedrock veins
-Quest at HV for Bedrock Miner
> Bedrock miner for the moon

- config/carryon-common.toml
- config/ftbquests/quests/chapters/mv__medium_voltage.snbt
-Fix Electrolyzer quest
-Fix Oilsands quest
-Fix for LSB lang format
-Adding quest for CPU Chip
> Fixes for MV Quest

- CHANGELOG.md
- kubejs/server_scripts/tfg/events.js
Allows medicine to work if cheats are disabled.
using player.runCommandSilent() does not work with cheats disabled. But, server.runCommandSilent() does.
> - Fixed pill behavior with cheats off

- kubejs/server_scripts/gregtech/recipes.js
Just packer recipes to make compacting sticks easier
Don't know if the I put the code in the right place, but It's working fine
Stick Packing easier and automatable
Can maybe conflict with some future packing recipe
Discord user: JeanRdS
> Stick Bundling

- config/ftbquests/quests/chapters/ev__extreme_voltage.snbt
- config/ftbquests/quests/chapters/gregtech_energy.snbt
- config/ftbquests/quests/chapters/hv__high_voltage.snbt
- config/ftbquests/quests/chapters/iv__insane_voltage.snbt
- config/ftbquests/quests/chapters/luv__ludicrous_voltage.snbt
- config/ftbquests/quests/chapters/uv__ultimate_voltage.snbt
- config/ftbquests/quests/chapters/zpm__zero_point_module.snbt
Add lang file for energy chapter
Add WIP on Quest Chapters
Add a quest to explain the outdated quests
> Quests work (Langfile, WIP)

- kubejs/server_scripts/tfc/recipes.machines.js
- kubejs/server_scripts/tfg/recipes.miscellaneous.js
This will remove the Scaffolding conflicting recipe with Paintings and fix the Wine Glass conflicting with Jar
This will fix the issue #1140 
Kinda hard to find a workaround, Wine Bottles were conflicting with 2 Jar recipes (Hematitic and Silica glass batch), so I changed the Jar recipe instead. Scaffolding frame recipe in the Assembler is just unnecessary, so I removed it.
> Conflict issues fix

- CHANGELOG.md
- kubejs/data/tfg/loot_tables/blocks/piglin_disguise_block.json
> Updated changelog

- kubejs/server_scripts/main_server_script.js
- kubejs/server_scripts/tfclunchbox/recipes.js
- kubejs/server_scripts/tfclunchbox/tags.js
- pakku-lock.json
Refactored KubeJS recipes for GT compatibility  
lunchbox update into Pakku
fixed bowl bug
fixed dupe food bug
> lunchbox update into Pakku

- kubejs/server_scripts/create_additions/recipes.js
- kubejs/server_scripts/gregtech/recipes.js
We both know what this is about , here , now that liquids can be drank by blaze burner , I won't add the straw recipe today so either wait god knows how long or add it yourself .
> Liquid burning

- pakku-lock.json
Continuing on from @Pyritie's work updating Pakku Mods, Game launches successfully
Need TFG-Core to update before this will work on its own,
Currently need to take a locally built TFG-Core latest branch source and replace tfg-core 0.6.8 with that jar,
> Updated more mods

- kubejs/data/railways/loot_tables/entities/conductor.json
This will remove the andesite alloy from the conductor loot table
> Condutor fix

- config/ftbquests/quests/chapters/hv__high_voltage.snbt
Add cetane boosted diesel and certus quartz
> Add cetane boosted diesel and certus quartz

- kubejs/startup_scripts/gtceu/machines.js
> Adding the LSP Structure

- CHANGELOG.md
- kubejs/server_scripts/afc/recipes.js
- kubejs/server_scripts/tacz/recipes.ammo.js
- kubejs/server_scripts/tfg/recipes.food.js
- kubejs/startup_scripts/gtceu/materials.js
added kelp and seaweed drying to electric oven (#1315)
added tfc properties to lead
added lead nugget crafting in anvil
added 45-70 crafting in lv assembler
fixed afc wood stomping barrel recipes
> Bug fix/Adding in some missing recipes

- defaultconfigs/create-server.toml
- defaultconfigs/greate-server.toml
create bug fix (steam engine and shafts)
_This section describes what this PR is about. It should be a clear and concise description concerning what this PR is for, why this PR is needed, and why it should be accepted._
_Linking an issue can be used alternatively to writing a description._
CREATE BUG FIX (VALUES AND GREATE SHAFTS VALUES FIXED)
_Any implementations in this PR that should be carefully looked over, or that could/should have alternate solutions proposed._
_A short description of what this PR added/fixed/changed/removed._
_For correct linking of issues please use any of the Closes/Fixes/Resolves keywords. Example: When a PR is fixing a bug use "Fixes: #number-of-bug"_
_This section is for screenshots to demonstrate any GUI or rendering changes, or any other additional …
> CREATE BUG FIX

- pakku-lock.json
_This section describes what this PR is about. It should be a clear and concise description concerning what this PR is for, why this PR is needed, and why it should be accepted._
_Linking an issue can be used alternatively to writing a description._
_Any implementations in this PR that should be carefully looked over, or that could/should have alternate solutions proposed._
_A short description of what this PR added/fixed/changed/removed._
_For correct linking of issues please use any of the Closes/Fixes/Resolves keywords. Example: When a PR is fixing a bug use "Fixes: #number-of-bug"_
_This section is for screenshots to demonstrate any GUI or rendering changes, or any other additional information that reviewers should be aware of._
_This section is for defining possible compatibility …
> cc tweaked pakku update

- config/ftbquests/quests/data.snbt
Hopefully this will future proof the issue of quests being not completed even though the tasks are done
This one will need a massive announcement and asking for feedback. It shouldn't fix the already bugged quest but hopefully will prevent any future one.
> Change the config of FTBQuests to be back to linear

- kubejs/server_scripts/tfg/recipes.food.js
> Fix soy bean #1607

- kubejs/startup_scripts/minecraft/modifications.js
makes popped chorus fruits edible
> make popped chorus fruit edible

- config/emi.css
> Disable Batch Rendering

- kubejs/server_scripts/ad_astra/recipes.js
- kubejs/server_scripts/gregtech/recipes.js
- kubejs/server_scripts/gregtech/recipes.machines.js
- kubejs/server_scripts/tfg/recipes.miscellaneous.js
- kubejs/server_scripts/tfg/recipes.nuclear.js
Hopefully everything is removed so I can update Mars on the server
> Removing all the commented out for Mars Update

- kubejs/server_scripts/soulbound/recipes.js
> naughty naughty illegal lang

- kubejs/server_scripts/gregtech/recipes.machines.js
> Fix recipe Ostrum Fab

- kubejs/server_scripts/tfg/recipes.rocks.js
- kubejs/startup_scripts/tfg/blocks.js
- kubejs/startup_scripts/tfg/blocks.space.js
Tiny PR to fix some things for the stone additions
- Wrong/Missing textures
- Added Slab to Wall chiseling recipes.
> Texture fixes + slab to wall chiseling

- pakku-lock.json
Adds the more mcmeta mods that allow for a lot more texture features.
[moremcmeta-emissives](https://www.curseforge.com/minecraft/mc-mods/moremcmeta-emissive-forge)
[moremcmeta](https://www.curseforge.com/minecraft/mc-mods/moremcmeta)
> moremcmeta

- kubejs/assets/tfg/blockstates/evaporation_tower.json
- kubejs/assets/tfg/models/block/casings/machine_casing_stainless_evaporation.json
- kubejs/assets/tfg/models/block/machines/evaporation_tower.json
- kubejs/assets/tfg/models/item/evaporation_tower.json
- kubejs/startup_scripts/gtceu/machines.js
- kubejs/startup_scripts/gtceu/recipe_types.js
Adding textures and disabling Evaporation Tower from Kubejs
> add evaporation tower and nuclear turbine

- kubejs/server_scripts/gregtech/utility.js
- kubejs/server_scripts/tfg/recipes.biochem.js
- kubejs/startup_scripts/ad_astra/materials.js
- kubejs/startup_scripts/main_startup_script.js
Adds recipes for all of the growth chamber blocks and items.
Next will be to actually start adding biochem recipes :3
> Recipes for the Growth Chamber
