TerraFirmaGreg-Team/Modpack-Modern

kubejs/server_scripts/sb/recipes.js

изменил тэг инструментов для крафта в sb
поменял тэг #minecraft на #tfc

изменил тэг инструментов для крафта в sb

---

kubejs/server_scripts/ae2/recipes.js
kubejs/server_scripts/ae2wtlib/recipes.js

_В этом разделе описывается суть данного PR. Это должно быть четкое и краткое описание того, для чего предназначен этот PR, почему он необходим и почему его следует принять._
_Связывание проблемы можно использовать вместо написания описания._
нужно изменить неправильный крафт беспроводного терминала и вернуть крафт остальным терминалам 
_Любые реализации в этом PR, которые следует тщательно изучить или для которых могут/должны быть предложены альтернативные решения._
для возвращения крафтов остальных терминалов заменил dense_energy_cell на литиум батарею hv как в крафте беспроводного крафтинг терминала 
_Краткое описание того, что добавлено/исправлено/изменено/удалено в этом PR._
_Для правильного связывания проблем используйте любое из ключевых слов Closes/Fixes/Resolves. Пример: когда PR …

Исправление крафтов терминалов AE2

---

kubejs/server_scripts/tfc/recipes.js

решения тикета 279 связанного с отстутствием крафта алебастровых  кирпичей
сделал крафты , **требуется выключить использование инструментов в крафте**
Исправления: #279

крафты  через  гипс

---

kubejs/server_scripts/gregtech/recipes.js

Fix issue for uncraftable assembler recipes, namely Long Distance Fluid/Item Pipelines from GT.
I remove the old recipe and add a new one, I don't know anything about kubejs, but maybe I should have modified it instead? Anyway the fix was halfing all the inputs and outputs of the recipe. The Long Distance Pipelines only stack up to 32.
Fixes #489, #314 and #361.
None.
Probably none, I've seen in the latest version of GregTech the recipe didn't change.

fix long distance pipelines

---

kubejs/server_scripts/tfc/recipes.js

Fixed the crucible recipe for Red Alloy to be the same as gregtech (1 copper + 4 redstone)

Fixed red alloy crucible recipe

---

kubejs/startup_scripts/tfc/constants.js

Added quern recipes for graphite, because "why can't I use my raw graphite to make kaolin clay" is a frequent question in the discord.
They have the same results as the furnace.

Added quern recipes for graphite

---

kubejs/server_scripts/gregtech/recipes.js

This changes all arc furnace and macerator recycling recipes for LV machines to output steel ingots / dusts instead of red / blue steel. An alternative to @Pyritie's #643 :-) 
You can match recipe IDs by regexp, yay.
No more exploits.

Fix LV recycling recipes to produce basic steel.

---

kubejs/server_scripts/create/recipes.js

Механизм точности в ассемблере, потому что стандартный рецепт креэйта боль, тем более когда ты уже в весь в грегтехе
The precision mechanism is in assembler, because the standard recipe for create is a pain, especially when you are already in full at gregtech

precision mech in assembler

---

kubejs/server_scripts/ae2/recipes.js
kubejs/server_scripts/gregtech/recipes.js
kubejs/startup_scripts/ae2/constants.js

This PR contains 5 commits.
1. It changes the costs of AE2 covered, dense and smart cables so the 3:1 ratio for fluix cables is reduced to 1:1.
* Covered cables should not be 3x the price for the same functionality. 
* The 3x cost makes it unnecessarily painful and expensive to run dense cable to where it's needed.
1. It re-enables AE2 cutting knives and adds recipes for them.
* This allows AE parts like interfaces to be renamed easily and cheaply.
1. It removes the in-world transformation recipe for AE2 fluix crystals.
* Mixer recipes for fluix crystals are buffed to match in-world transformation recipe costs.
* Mixer recipe duration is reduced.
* Note that the create mixing recipe for fluix crystals still remains.
1. It adds self-crafting recipes for all super tanks and chests.
* This …

Various fixes for 0.7.14

---

kubejs/server_scripts/minecraft/recipes.js

Added an early glowstone recipe so people can have light bulbs at the same time they have electricity.
It's intentionally annoying so the hv macerator recipe is better once that is available.
Stone Dust (from ore washing) + redstone + sulfur + sodium + 1B creosote + 1B distilled water = 1 glowstone dust

Adds early glowstone recipe

---

kubejs/server_scripts/gregtech/recipes.js

Crucible always does 1 copper + 4 redstone = 5 red alloy, so to prevent duping, I changed the gregtech recipes to match.
I also fixed the arc furnace + macerator recipes for steam machines so they return the correct items.
etc

Added recipes to stop duping of red alloy + steam machines

---

kubejs/assets/tfc/patchouli_books/field_guide/en_us/entries/tfg_ores/ore_basics.json

Removed the ore spreadsheet link from field guide, as per #675

Remove ore spreadsheet link from field guide

---

kubejs/server_scripts/gregtech/recipes.js

Maintenance hatches no longer produce red/blue steel when recycled.
Recipe name does not include "lv_" so the regexp missed it :-(

Fix maintenance hatch recycling recipes too.

---

kubejs/startup_scripts/tfc/constants.js

Fixed a recipe overlap with charcoal in a macerator, so now it goes like this:

Fix charcoal in macerator overlap

---

kubejs/server_scripts/tfc/recipes.js

Added recipes for growing #tfc:plants in greenhouse. For decoration purposes
Reused generateGreenhouseRecipe in kubeJS iterating over tag #tfc:plants
Now all plants can be grown in greenhouse. 
Probable not, maybe some intersections of recipes in future if tags will have same plants

Added greenhouse recipes for tfc plants tag

---

kubejs/server_scripts/gregtech/recipes.js

This makes the quantum mainframe recipe take 24 2x annealed copper wires instead of 48 1x, because the latter only stack to 32.

Use 2x annealed copper wires in ZPM mainframe recipe.

---

kubejs/server_scripts/framed_blocks/recipes.js

It's just aesthetically different from a crate, other then it can be used with create
new recipe(s):

Craft recipe for framed chest so it isn't cheaper then the alternatives

---

kubejs/server_scripts/gregtech/tags.js

- Stops creosote treated planks from eating all the creosote in a barrel
- Allows treated wood pipes to be crafted
#473

Creosote treated planks fixes

---

defaultconfigs/firmalife-server.toml
kubejs/assets/tfc/patchouli_books/field_guide/en_us/entries/firmalife/irrigation.json
kubejs/server_scripts/firmalife/recipes.js
kubejs/server_scripts/tfc/recipes.js
kubejs/startup_scripts/firmalife/constants.js

It Just Works™
Added recipes for the pumping station
Added machine recipes for the sprinkler and pipes
Also fixed #700, added circuits to those mixer recipes
Fixes #491
Update firmalife to 2.1.15
Sprinkler can be used
I have not tested absolutely everything in firmalife, but I looked through the recipes and they all look ok. I did have to change two new ones they added (using different bronzes to make the pumping station)

Fix sprinklers + fix bread and yeast starter recipe conflict

---

kubejs/assets/tfc/patchouli_books/field_guide/en_us/entries/tfg_tips/blast_furnace_tips.json

Adds a page with some tips on making/automating a TFC blast furnace.
Can prevent players who haven't followed the blast furnace crafting line extensively from using a lot of kaolinite on a full-sized blast furnace. Also brings tips previously only found in the Discord into the game manual. Mainly useful for those who have played TFC before and aren't as familiar with Create/GT.

Add blast furnace tips entry

---

kubejs/server_scripts/tfc/tags.js

Stick bundles can now be turned into charcoal in the coke oven and pyrolyse oven.
Stick bundles now have the #minecraft:logs_that_burn tag, which is the same tag given to TFC logs to allow them to be used in coke/pyrolyse ovens.
Stick bundles could be used in TFC charcoal pits to make charcoal, so this allows the coke oven to fully replace TFC charcoal pits.
The #minecraft:logs_that_burn tag appears to confer various other tags, including the #minecraft:logs tag. This allows the stick bundle to be used in crafting recipes that require #minecraft:logs, namely some create recipes and macerating into wooden pulp/lathing into long wooden sticks. None of these recipes allow for duplication exploits, and the pulp/long wooden sticks can be created from the constituent sticks already (at a better …

Allows stick bundles to be used in the coke oven

---

kubejs/server_scripts/create_connected/tags.js
kubejs/server_scripts/gregtech/recipes.js
kubejs/server_scripts/main_server_script.js

All colors of glass (and tinted glass as well) can now be macerated in the macerator or hammered in the crafting window to dust. Colored glass panes work as well.
The default maceration recipes for glass and glass panes were removed and replaced with #forge:glass and #forge:glass_panes.
Most TFC sands by default output colored glass, while previously only clear glass could provide glass dust (needed for vacuum tubes). This means you had to go out searching for white sand for silica batches to progress into LV. Allowing colored glasses allows all sand types to be used for glass dust.
The Create bamboo and cherry glass panes are tagged with #forge:glass_panes, so show up in the list of possible inputs for tiny glass dust. However, these items are hidden from EMI and have no recipes, so …

Allows all colors of glass to be macerated/hammered to dust

---

kubejs/server_scripts/firmaciv/recipes.js

Fix for the issue [$615 Steel Duplication Glitch via Anchors](https://github.com/TerraFirmaGreg-Team/Modpack-Modern/issues/615). There was the same problem with `Cannon barrel` and `Unfinished Navigation Clock`. They are made from double plates, but recycle into 4 ingots/dusts.
It seems to be a deeper issue with generating wrong recycling recipes for items that are made in an anvil from double plates.

Fix dupes via recycling firmaciv items

---

kubejs/server_scripts/gregtech/recipes.js

creates a flux recipe for the macerator and forge hammer, to live alongside the quern and manual hammer recipes.
this recipe may not be incredibly necessary, but it may fill out some area in the Steam Age, and also follows the intuitive idea that anything you can do in the quern you can do in the macerator. the forge hammer recipe was also added as you can craft it with a hammer. the actual recipe duration is up for debate i suppose, but i picked something moderately reasonable: quite a bit faster than the quern, but not nearly instant.
N/A

create fluxstone recipes in macerator and forge hammer

---

kubejs/server_scripts/gregtech/recipes.js

Added rich coal recipes with the same ratio you'd get resource-wise, with 10% off the duration!
I felt like you were being punished for getting better coal from the ground, so i decided to add recipes to the coke oven and pyro oven that basically skipped the furnace. I also decided that it should be a little bit better, so i gave a small (10%) duration decrease. 
This should be a moderately helpful set of recipes in terms of figuring out how you can use the rich coal you find.
N/A

create some rich coal recipes in coke oven and pyro oven

---

kubejs/server_scripts/tfc/recipes.js

Fixes a recipe conflict for wool cloth in the assembler by adding a circuit to it.
Now wool blocks can be crafted instead of wool cloth in the assembler.
I haven't personally tested the change yet but @KorGgenT did and it works fine for him.

Fixes wool cloth recipe conflict

---

kubejs/server_scripts/gregtech/recipes.js

This PR changes the behaviour of using the mechanical press to get plates. Instead of having a 80% chance of succeed and when failing returning nothing, when it fails, the player is awarded with 1 small dust of the material. This way press is still a gambling method of getting plates but when it fails at least you get something in return (even if you'd need 4 fails to get another attempt)
The pressing recipe of create only accepts a % based chance of multiple outputs, this means that adding a small dust to the array of outputs meant that there was a slight chance for the player to end up with 1 plate and 1 small dust, breaking the laws of conservation of matter
To fix this, the recipes for pressing ingots into plates is now a sequenced assembly that only requires 1 press action to get the …

Get small dust from failed pressing

---

kubejs/server_scripts/tfc/recipes.js
kubejs/startup_scripts/tfc/constants.js

Cassiterite dust and cassiterite sand dust now correctly melt down to 144 mb and 108 mb respectively of tin. All stages of ore processing have also been edited, making all stages correct proportionally to cassiterite and cassiterite sand's correct richness percentage (100% and 75% respectively).
A new function was created in tfc/constants to calculate the yield for "processed" ores. If the percent yield plugged in for a "processed" ore is greater than 100, it calculates the correct percent per item by roughly "estimating" how many output items would be produced by macerating the ore and then dividing the percentage by that. This works correctly for cassiterite and cassiterite sand. 
The only heating recipes that now use the new function are the heating recipes for crushed, purified, and …

Fixed cassiterite heating "exploit"

---

kubejs/assets/tfc/patchouli_books/field_guide/en_us/entries/tfg_tips/blast_furnace_tips.json
kubejs/server_scripts/tfc/data.js

Fixes the issue where crushed/processed ores do not heat up and thus can never melt into anything in the crucible/blast furnace. Also removed the page in the blast furnace tips that detailed which inputs would work, since all inputs should now work so the page is now irrelevant.
Added item heat values through makeItemHeatByTagPrefix() in tfc/data.js for the various stages of ore processing. This should not have any adverse affects, as far as I can tell, as it should only affect ores.
Now you can melt your purified ores directly into liquid, if you so desire. Although it is incredibly stupid to do so, but to each their own.

Adds heat values for items with valid heating recipes but no heat values

---

kubejs/server_scripts/create/recipes.js

This PR adds Automatic Scraping in Mechanical Age via the utilization of Sequenced Assemblies and Deploying a knife.
Implementation was made using KubeJS, utilizing a forEachRecipe call and filtering by the ``tfc:scraping`` type, this means that any other recipe added of type scraping will automatically get a Sequenced Assembly Version.
The amount of deployments needed is 16, which is the total amount needed in any scraping recipe in vanilla TFC.
Players can now auto-scrape without having access to the Cutter
None AFAIK

Automatic Scraping with Sequenced Assembly

---

kubejs/server_scripts/tfc/data.js

Adds glowstone as a TFC lamp fuel, it is usable in all types of lamps and burns forever, like lava. The upside is that it is not restricted to blue steel lamps, so you can use other TFC lamps for aesthetics.
Added gtceu:glowstone as a lamp fuel with a consumption rate of -1. This is identical to how lava in blue steel lamps works in the TFC code.
This allows TFC lamps (besides blue steel) to be a viable source of infinite light. They are aesthetically pleasing, so it is nice to keep them as an option. To me, it is balanced to allow it in all lamps, not just colored steels, since lava is infinite and glowstone is far harder to produce, offsetting the lower cost of allowing cheaper lamps such as bronze.

Add glowstone as infinite lamp fuel

---

kubejs/server_scripts/gregtech/recipes.js

LV casings are now always 8 steel plates, both in a crafting grid and in an assembler. Everything LV arc furnaces/macerates down into 8 steel ingots/dust.
LV hulls now require 2 red steel plates instead of 2 wrought iron plates.
MV is unchanged, and then polyethylene can be used to make casings without the red steel.
I used the temporary code from 0.7.16 that @/fluffle wrote.
The colored steel is still required, but it's not nearly as annoying as before. Blue steel is popular for tools and lamps so people will want to make a bunch of that anyway.
I liked that people were automating their TFC blast furnace before because of how much steel they needed.
The all colored steel change in 0.7.17 is very unpopular and some people aren't updating to the latest version because of this change. I …

Changed LV casing/hull recipes (again)

---

kubejs/server_scripts/tfc/data.js
kubejs/server_scripts/tfc/recipes.js

Adds drying recipes to seaweed and kelp, just like fresh seaweed and giant kelp flowers have currently.
They are set to 200 temperature, which is the same defined for the recipes in tfc:
https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/1.21.x/src/generated/resources/data/tfc/recipe/heating/food/dried_seaweed.json
And their corresponding item heat capacity is set to 1.0, just like the existing seaweed/kelp recipes.
This is related to this issue: https://github.com/TerraFirmaGreg-Team/Modpack-Modern/issues/464
Maybe instead of hardcoding the recipes a tag system could be added to the seaweeds and kelps, but alas this is my first time working with kubejs and I have no idea how to set that up. If there is no big push for it, this should cover most bases.
Recipes to dry kelp and seaweed …

Add seaweed and kelp drying recipes

---

kubejs/server_scripts/gregtech/recipes.js

Fixes the TFC Hanging Signs exploit that allowed users to input 2 ingots worth of metal into making them and then getting 3 ingots worth of metal back by using either an Arc Furnace or Macerator. This was due to the hanging signs being made in such a large quantity by cheap ingredients that the lowest possible output granularity (tiny dusts/nuggets) were too large to capture the material put into their manufacture.
Recipe for Macerating black steel acacia hanging signs before this change:
Recipe after this change:
Since adding even more granularity didn't make much sense, I just made the recipe outputs for hanging sign recycling with the Macerator & Arc furnace, which originally gave 1 full nugget's worth (16mB) of metals back, to give the 16mB only 37.5% of the time.
This should roughly …

Hanging Sign Metal Dupe fix

---

kubejs/server_scripts/tfc/tags.js
kubejs/startup_scripts/tfc/constants.js

This PR fixes collapsible bricks. Bricks are supposed to be sturdier than raw/smooth rock blocks. But even if bricks are not collapsible, brick slab blocks are for some reason. And because they can be used for decoration, it can bring a lot of pain.
Brick slab blocks don't collapse
Constant `global.TFC_ROCK_SLAB_BLOCK_TYPES` and tags `tfg:rock_slabs`, `tfg:rock_stairs`, `tfg:rock_walls` got changed contents. But search showed no other usage for them besides in the changed file in the code section for collapsible stuff, so it must be okay.

Fix collapsible brick slab blocks

---

pakku-lock.json
pakku.json

This fixes #864, #863, #862, #861, #860, #859, #858 and #857
After the creation of the "PakkuLockChecker" in the tools repository, i utilized its output to review and modify the Pakku-lock file to ensure the following things:
1. If a mod exists in both Curseforge and Modrinth, Add them bod
* This rule is avoided if the version differences are TOO big (too big stands for a missing version on the Minor category (x.*Y*.z)
* The highest version takes priority
* If the highest version exists in one platform and not the other, add the next highest that exist in both platforms, as long as the version change is NOT minor
2. If a mod IS indeed in both Curseforge AND Modrinth, ensure BOTH files point to the same version.
* This avoids versioning issues present in the export builds
I also modified …

Server Pack Fix

---

kubejs/server_scripts/afc/recipes.js
kubejs/server_scripts/gregtech/recipes.materials.js
kubejs/server_scripts/tfc/recipes.materials.js
kubejs/server_scripts/vintage_improvements/recipes.js

- Moved ore processing recipes out of TFG-Core, into Kubejs
- Added a workaround for the greate bug involving poor ores and the millstone/crushing wheel
- Fixed poor ore crushing rates
- Fixed bulk washing recipes for pure/impure dusts to match the LV ore washer ones
- Fixed VI centrifuge recipes for pure/impure dusts to match the LV centrifuge ones
Goes in tandem with https://github.com/TerraFirmaGreg-Team/Core-Modern/pull/25
Consistency!

Refactored ore recipes and moved them out of TFG-Core

---

kubejs/assets/tfc/patchouli_books/field_guide/en_us/entries/getting_started/finding_ores.json
kubejs/assets/tfc/patchouli_books/field_guide/en_us/entries/getting_started/primitive_anvils.json
kubejs/assets/tfc/patchouli_books/field_guide/en_us/entries/mechanics/anvils.json
kubejs/assets/tfc/patchouli_books/field_guide/en_us/entries/mechanics/blast_furnace.json
kubejs/assets/tfc/patchouli_books/field_guide/en_us/entries/mechanics/glassworking_applications.json
kubejs/assets/tfc/patchouli_books/field_guide/en_us/entries/mechanics/prospecting.json
kubejs/assets/tfc/patchouli_books/field_guide/en_us/entries/mechanics/quern.json
kubejs/assets/tfc/patchouli_books/field_guide/en_us/entries/tfg_ores/hazards.json
kubejs/assets/tfc/patchouli_books/field_guide/en_us/entries/tfg_ores/ore_basics.json

Update field guide [#853](https://github.com/TerraFirmaGreg-Team/Modpack-Modern/issues/853#issue-2997290737)
getting_started/finding_ores
Surface indicators amounts - 10mB to 16mB
Casting amounts - 100mB to 144mB
Change/fix pickaxe recipe. 
Add page and recipes for saw blade for wood, and chisel for working with stone as important unlocks with metal.
Moved Welding from Anvil page to Primitive Anvil page - you'll need to weld on a stone anvil before getting a metal anvil that can work ingots. Update welding links.
Prospecting
Update bad link to ores and minerals to tfg_ores/index
Remove invalid range reference for small indicators
Fix prospector's pick recipe pages
tfg_ores/ore_basics
Yeet hammer references for ore mining, mention it doesn't drop ores
Add crushed ore from quern/millstone, …

Update field guide for 0.9

---

defaultconfigs/tfc-server.toml

TFC cost per ingot was 100mB, and the small vessel held 3000mB for up to 30 ingots by default. TFG changed the ingot amount to 144mB, but small vessel capacity never got changed.
~~Changed smallVesselCapcity from 3000 to 4608, or 32*144. Because 32 is nicer than 30.~~
Alternative options - 4,320 (30 * 144), 3024 (21 * 144), or 2880 (20 * 144), to divide evenly by 144.
Updated: smallVesselCapacity 3000 to 3024 (divides evenly into 21), crucibleCapacity from 4000 to 4032 (divides into 28), to stay closest to previous values.

Update small vessel capacity

---

.pakku/server-overrides/README.md
pakku.json

#889 
Adds a new readme file with details on how to start the server
Fixes #889 
Starting the server should be pretty much straight forward, i think *most* machines should be able to run the .bat file using the BASH command.
None

Add README file to server overrides

---

config/ftbquests/quests/chapters/questssteam_age.snbt
config/ftbquests/quests/chapters/queststfc_tips.snbt
kubejs/server_scripts/vintage_improvements/recipes.js

Fixes #959
- Made Vacuum Chamber craftable with ULV Casings rather than hulls (being the precursor to ULV vac tubes I think this is fair). This lets them craftable without rubber-requiring red alloy cables which was the issue.
- Quest updates to show rubber line changes more clearly (remove dependency on extractor, change it to Vac chamber)
Fixes #959
N/A
N/A

FIX: Rubber softlock

---

kubejs/assets/tfc/patchouli_books/field_guide/en_us/entries/getting_started/finding_ores.json
kubejs/assets/tfc/patchouli_books/field_guide/en_us/entries/roadsandroofs/concrete_roads.json

Field guide updates:
Getting started, ores and casting - Mentioned Small Vessel capacity and loss for overflow. Added wooden tongs page, to pick up hot vessel.
Roads and roofs, concrete roads - Updated instructions on how to obtain liquid concrete mix to pour in TFG, added highlights for important points in paragraphs.

Field guide updates - Getting Started/Casting (Wood Tongs, Small Vessel Capacity), R&R/Concrete Roads (TFG Instructions)

---

kubejs/server_scripts/gregtech/recipes.js

Per https://github.com/TerraFirmaGreg-Team/Modpack-Modern/issues/897, fuel consumption rates in a large bronze boiler was extremely inefficient when compared to an equivalent amount of single block boilers for steam generation. This resulted in (unlimited) lava being the only viable fuel source for large bronze boilers. With infinite lava being somewhat harder to obtain in 0.9, this will allow for alternative fuel sources to be reasonably usable.
Fuel burn time for large boilers increased by a factor of 9 across all fuel recipes.
Rough math is here - https://docs.google.com/spreadsheets/d/1sUxEC2wlal7e6ZZL-gg3Efy8ZewM7zUoNVPOG8WlejE/edit?usp=sharing
Previously, an equivalent of 26.6 liquid steam boilers to a 100% large bronze boiler to generate 800mB/T steam would cost 37 mB/s of creosote …

Buff Large Boiler Fuel Efficiency

---

kubejs/server_scripts/create/recipes.js
kubejs/server_scripts/gregtech/recipes.machines.js
kubejs/server_scripts/tfg/tags.js
kubejs/server_scripts/vintage_improvements/recipes.js

Added alternative recipes for wooden crates, copper diving boots and the helve hammer that use wrought iron instead of cast iron.
Added a new tag that includes cast/wrought iron double ingots (this is used for the helve hammer recipes) and made use of the create deco tag for the copper diving boots.
This change makes it so that wrought iron can be used as well as cast iron for these early game recipes.

Add wrought iron alternatives for early game cast iron recipes

---

CHANGELOG.md
kubejs/assets/tfc/patchouli_books/field_guide/en_us/entries/getting_started/finding_ores.json
kubejs/client_scripts/tooltips.js
kubejs/server_scripts/hotornot/recipes.js
kubejs/server_scripts/tfc/recipes.js

Changed wooden tongs recipe from shapeless to shaped - People seemed to commonly get confused about how to cast their first metal tools now that vessels with molten metal are too hot to hold, thinking they need a workbench 3x3 crafting grid to make wooden tongs and can't get one without casting a metal saw.
Added a crafting recipe for jar lids, since working tin on an anvil is rather difficult, and jar lids are consumables. Crafting recipe results in half yield (8x) vs forging (16x).
~~Salt (dust) and Salt (powder) have the same name. Changed Salt (powder) to Table Salt~~ This implementation didn't seem to work. In draft until I resolve or remove. (Or if someone knows how to do this right please let me know!)
Tested in game for above recipes, they work fine.

Some recipe changes

---

config/carryon-common.toml

Added the afc chests to Carry On's whitelisted blocks.
Explicitly added the arborafirmacraft chests to the whitelist.
The afc chests can now be picked up by players just like the tfc ones can.
**Enter your Discord nickname, if your PR is successfully accepted, you will be given the Contributor role**
noble_was_taken

Updated carryon-common.toml for afc

---

CHANGELOG.md
kubejs/server_scripts/create/recipes.js
kubejs/server_scripts/firmalife/recipes.js

Some recipes overlapped and prevented the use of other similar recipes, such as trying to mix dough in a mixer would result in making more yeast instead, and windmill bearing in assembler resulting in gantry carriage instead.
- Removed leftover create.mixing recipes that were for the old mechanical mixer
- Added programmed circuit numbers for windmill bearing and gantry carriage assembler recipes.

Overlapping recipe fixes

---

config/invtweaks-client.toml

there's a silly bug where if you hit the 'sort inventory' key in the crucible, you get stacks of ingots where there should only be single ingots. this should be prevented
added all of the tfc screens with a wildcard glob, affected screens (some of which aren't actually inventories, but that shouldn't matter) are found at:
https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/1.20.x/src/main/java/net/dries007/tfc/compat/jei/JEIIntegration.java#L43-L53
disallow inventory tweaks' sort inventory function in tfc screens
it is somewhat possible a tfc addon might put their screens in the same space, if necessary the match can be made more specific.
scenarios tested:
you CANNOT use a hotkey to sort in vessel, large vessel, or crucible.
untested: it should also prevent sorting in the cooking …

disallow inventory tweaks' sort inventory function in tfc screens

---

kubejs/server_scripts/vintage_improvements/recipes.js

Helve hammer now create tin plate from tin double ingots
I just added missing tin recipe for hammering
Fixes #1064
Recipe screenshot:
Not compatible with tin double ingots from TerraFirmaCraft, only with GT double ingots, tho must be fine with game
discord: ownog
P.S vscode add some prettienes to json formatting, I didn't changed it, because i think it's for greater good. Is it okay or i must revert it?

Tin hammering recipe

---

CHANGELOG.md
config/invtweaks-client.toml

#1115 
same as #1045, add the appropriate gui class to inventory tweaks rewhozited, so that it doesn't render the sort button, or allow the manual sort hotkey
fixes #1115 
if it turns out there's another create ui with inventory slots, it'll need to be handled separately, this was a targeted fix to only the toolbox unlike when i said 'no u' to all of tfc's non-chest guis.

add the create toolbox to the list of unsortable inventories

---

kubejs/server_scripts/gregtech/recipes.js

- Glowstone abs recipe
- Gives an direct way to get liquid glowstone (used in nano cpu wafers and decoration)
ABS glowstone recipe

ABS glowstone recipe

---

kubejs/server_scripts/ad_astra/recipes.js
kubejs/server_scripts/gregtech/recipes.js
kubejs/server_scripts/gregtech/recipes.removes.js
kubejs/server_scripts/railways/recipes.js
kubejs/server_scripts/tfg/recipes.miscellaneous.js

#1290 Add circuit 2 to all rocket recipes that hadn't a circuit after verifying no conflict
#1295 Fixing all the dumb snow stuffs
#1302 Putting Iron rotor in place of the Create one
Fixing the Autoclave MV recipe to make Rose quartz while skipping the ore
Fixing all water type into ice for 144mb and not 100mb to keep consistent with GTceu

Small fixes for many different recipes

---

kubejs/assets/tfc/patchouli_books/field_guide/pt_br/categories/beneath.json
kubejs/assets/tfc/patchouli_books/field_guide/pt_br/categories/tfg_ores.json
kubejs/assets/tfc/patchouli_books/field_guide/pt_br/categories/tfg_tips.json
kubejs/assets/tfc/patchouli_books/field_guide/pt_br/entries/firmalife/irrigation.json
kubejs/assets/tfc/patchouli_books/field_guide/pt_br/entries/tfg_ores/hazards.json
kubejs/assets/tfc/patchouli_books/field_guide/pt_br/entries/tfg_ores/ore_basics.json

This PR adds Brazilian Portuguese (`pt_br`) language support to the Field Guide by:
- Adding `pt_br` translations for all entries in the `categories` folder.
- Adding `pt_br` entries specifically for the **Irrigation**, **Hazards** and **Mining** sections.
These additions aim to improve accessibility and localization for Portuguese-speaking players.
- Translated all JSON files in the `categories` folder to `pt_br`, maintaining original structure and formatting.
- Localized new entries for Irrigation and Hazards with accurate terminology consistent with the modpack context.
- Ensured consistency and correctness across the newly added translations.
- Added full `pt_br` language support for the `categories` folder.
- Added new `pt_br` entries for Irrigation and Hazards in the Field Guide. …

Begin Portuguese (Brazil) translation of Field Guide content

---

kubejs/startup_scripts/gtceu/materials.js

* Makes thorium pink
* I used a colorpicker
* Thorium is now Pink
* I made it pink to turn it into an Obscure Mindustry reference, plus, I saw some developers where looking to recolor it to differentiate from another material.
If you don't like pink then this may be a downgrade

Pink Thorium

---

config/modernfix-mixins.properties

As per my testing, Minecraft's launch memory use was reduced around 1 GB and around 15 seconds faster.
Less memory use overall.
CAUTION! This may add other side effects like crashes or bugs it needs more testing.
Discord: victordlp8

Added some performance oriented options to ModernFix

---

kubejs/server_scripts/tfg/tags.facades.js

Between all the items that can be used to make a GregTech facade, concrete is missing.
Since wood and gravel are available, I felt like concrete, a much more stable material, should be available as well.
Just added a tag representing concrete in to tags.facades.js
Concrete facades \o/
There is no `#minecraft:concrete`, so if any future mod adds blocks tagged `#forge:concretes`, it would be added to facade list as well, which may not be desirable.
**Discord nick:**
`theashenwolf`

Added concrete into facade materials

---

kubejs/server_scripts/tfg/recipes.supports.js

We should try to avoid GTm circuits that are used for basic materials.
Mainly #4 and #6
Put everything on #11 so it says harmonized

Fix circuit duplicate recipes for support beams

---

kubejs/server_scripts/tfc/data.js

Sets correct sizes and weights for mining hammers, wrenches, and spades as to not allow them to fit into chests
Bug report:
[https://github.com/TerraFirmaGreg-Team/Modpack-Modern/issues/1532](url)
Discord Nickname:
dimethyl

Fix mining hammer bug

---

CHANGELOG.md
kubejs/startup_scripts/tfc/constants.js

Remove quern/macerator recipes to turn cinnabar to redstone
Removed the recipe defined in global.TFC_QUERN_POWDER_RECIPE_COMPONENTS
Before this recipe generated free resources by crushing cinnabar to redstone, then centrifuging that redstone. E.g 10 cinnabar usually gives 5B mercury, but crushing this gave 40 redstone which centrifuges to 12B mercury + extra resources.
This recipe was added at some point, presumably for the early game as it was a quern recipe. But it seems redundant as you can just mine redstone and cinnabar is not required for progressing. It would be easy to add a similar recipe back in if it turns out there was a need for it.
Discord: spicy_noodle5

Remove cinnabar to redstone recipe

---

kubejs/server_scripts/afc/recipes.js
kubejs/server_scripts/afc/tags.js
kubejs/server_scripts/gregtech/recipes.js
kubejs/server_scripts/gregtech/recipes.removes.js
kubejs/server_scripts/tfg/recipes.food.js
kubejs/server_scripts/tfg/recipes.miscellaneous.js

-Add uniformisation for all the resins (Extractor, etc...)
-Nerf the Centrifuge of logs to MV so players have to make the LV Line
-Buff the LV line so it's faster
-Make Sticky resins and glue faster
-Change the centrifuge of Sticker Resin and Rosin into glue to be faster and increase biomass output
-Alternative recipe with extractor faster if needed
-Balance the wood gas
Do we keep wood gas for smoked food or change for a wood dust as an item?

Rework of all resins

---

kubejs/server_scripts/tfg/recipes.miscellaneous.js

You should have to make an Implosion Compressor and not skip by killing Enderman

Fix Pyrolyse Oven accepting other ender pearls

---

kubejs/data/tfg/dimension_type/moon.json

Moon Needed a light level of 12 or higher to stop ad astra mobs from spawning
I changed 1 line
Fixes #1587 
Tested in singleplayer.
Discord: NINAustinFett

Fixed Moon Light Level for Spawning

---

config/ftbquests/quests/chapters/questsmetallurgy.snbt

`quests.metal_age.red_blu` does work on a new worls, but when i imported my save from a previous version it was stuck. Having a checkmark guarantees that it will not be stuck
Changed exist task with checkbox
The quest/task is now guaranteed to be completable, as the automatic exist task didn't work as expected on existing saves that were migrated.
None
None

fix: Fixed quests.metal_age.red_blu

---

config/ftbquests/quests/chapters/questsmetallurgy.snbt

`quests.metal_age.redblu_anvil` has both red and blue steel requirements, however it seems more logical if only one is required as only one of both anvils is required
added `dependency_requirement: "one_completed"`
Only one of both paths is requried
None
None

fix: Fixed quests.metal_age.redblu_anvil requirements

---

.github/README.md

Fixed a broken link to README_IF_TRANSLATING.md in README.md The file was renamed earlier, but the link has not been changed

Fix link in README

---

kubejs/data/tfg/worldgen/configured_feature/mars/semiheavy_ammoniacal_water.json
kubejs/data/tfg/worldgen/noise_settings/mars_noise.json

semiheavy ammoniacal water block now has the correct tag
maps show the right color
See https://github.com/TerraFirmaGreg-Team/Core-Modern/pull/111

fix semiheavy concurrent with tfg core

---

kubejs/server_scripts/firmalife/recipes.js

Added Vat recipe for boiling salt water into salt, if any of the salt water-related recipes break in the future then this is the likely culprit
I was fully expecting the other salt water recipes to break but surprisingly it seems like they won't run if an invalid ingredient is present, which prevents recipe conflicts.

Bulk Salt Boiling

---

kubejs/server_scripts/tfg/tags.facades.js

add all cobblestone to be used as facades
added `forge:cobblestone` to the `facade_materials` list
Cobblestone to be valid option to make into facades.
i noticed every other material is tagged as `#tfc/rock/x` with x being something like "bricks" or "smooth" yet none of the cobblestone follows this tag structure, i'm unsure if this is intentional, so I have used forge:cobblestone to add it all to the facade list.
none that i can think of

added forge:cobblestone to facade_materials

---

kubejs/server_scripts/tfc/recipes.js
kubejs/server_scripts/tfc/recipes.materials.js
kubejs/server_scripts/tfc_grooming_station/recipes.js
kubejs/startup_scripts/tfc/constants.js

Add Flax as a valid option for the Jute Net
Replace input `tfc:jute_net` for `#tfg:burlap_fiber`
fix #1815

Jute net to be made with Flax

---

kubejs/server_scripts/tfg/recipes.food.js

The Food Processor recipe for Jam uses the tfc:sweetener tag now, allowing for making jam with honey in the food processor now.
Edited the recipes.food.js file and changed the food processor jam recipes to use tfc:sweetener instead of tfg:sugars
Honey can now be used to make jam in the food processor, just like in a vat (sugar water can be made with any tfc:sweetener)
**Discord: xaligal**

Switched tfg:sugars for tfc:sweetener in food processor jam recipes

---

kubejs/server_scripts/create/recipes.js
kubejs/server_scripts/create_factory_logistics/recipes.js

Packagers and Bottlers have their costs reduced by making them require metal casings rather than ULV Hulls.
Playing TFG with my friends we found out that the ULV hulls that are part of the packager/bottler recipes are prohibitively expensive, especially early game. With them being so crucial to the setting up of a logistics network, this PR addresses that by making the recipe require a casing rather than a hull (remove rubber dependency) and giving 2x returns for the crafts.
Additionally, the LV assembler cardboard recipe has also been buffed a bit to require less paper and glue because it's a tedious recipe to begin with. This should make it a lot less annoying to make.
Stock links/factory gauge recipes are left unchanged, as the automation of parts needed in them is a core mechanic of …

Create packager recipe buffs
